### ISSUE TITLE
Build instructions

### ISSUE THREAD

**Issue by SicariusNoctis** [vEnhance/napkin#1]
Thanks for making this available!

I think it would be useful to provide build instructions (via a Makefile?) and list non-typical CTAN package dependencies (e.g., prerex, diagrams [?], ...).

**Comment by vEnhance** [comment]
I'll try to do this eventually! For now, a quick response: you can build just by running `latexmk` assuming LaTeX and Asymptote are installed. I don't have a careful list of packages used but they can be found by reading preamble.sty. (I also think TeX Live has all or nearly all of them in default installations.)

**Comment by aDotInTheVoid** [comment]
Even with `texlive-full`, it cannot be compiled

Citation: [this](https://travis-ci.com/aDotInTheVoid/napkin/builds) attempt to build with travis

**Comment by SicariusNoctis** [comment]
^ Setting up some CI or versioned-releases is probably a good idea.

**Comment by vEnhance** [comment]
Now that Travis is working well with Napkin (with thanks to @aDotInTheVoid for help!), I'm marking this as done --- since in theory all the non-typical packages are committed into the repository now, it should suffice to run `latexmk` with a sufficiently new version of TeX Live. (Unfortunately, Ubuntu is pretty far behind in TeX live versions --- might need to upgrade that first.)

Feel free to re-open or start new issues if people run into other sorts of build woes.
