### ISSUE TITLE
The hint of v1.5's problem 51C "might" be wrong

### ISSUE THREAD

**Issue by simnalamburt** [vEnhance/napkin#10]
NOTE: This issue was actually found by @puzzlet

<br>

Problem 51C is:

> ![](https://user-images.githubusercontent.com/4435445/57856444-089c5980-7828-11e9-96f6-cbd561f094b2.png)

And hint of problem 51C is:
https://github.com/vEnhance/napkin/blob/1a3fc0a22b8323231064c52d119311c73a11d60b/tex/alg-NT/galois.tex#L614-L617

The description that the left side has a minimal polynomial of degree 7 is presumed to mean the polynomial below.

<img width="686" alt="
\[
\textrm{since } \cos7\theta = 64\cos^7\theta - 112\cos^5\theta + 56\cos^3\theta - 7\cos\theta \textrm{,}
\]
\[
1 = 64x^7 - 112x^5 + 56x^3 - 7x
\textrm{ if } x = \cos\left(\frac{2\pi}7 \right)
\]
" src="https://user-images.githubusercontent.com/4435445/57860713-4e5d2000-7830-11e9-9621-b34a644c0a59.png">

But I'm afraid it is not minimal polynomial since it is not irreducible.

<img width="808" alt="
\[
64x^7 - 112x^5 + 56x^3 - 7x - 1 =
(x - 1)(8x^3 + 4x^2 - 4x - 1)^2
\]
" src="https://user-images.githubusercontent.com/4435445/57860255-86179800-782f-11e9-8f4b-e687b8996e1f.png">

How can I easily solve 51C with Galois theory?

**Comment by vEnhance** [comment]
You're right, the given solution is plain wrong. I'll have to get back to you on how to fix it (if I can figure out at all :P ).

**Comment by vEnhance** [comment]
I finally dug up a link to a solution of a basically  identical problem and added it in (I figured I have put this off for so long now it is better to just get the link up rather than keep waiting), in
https://github.com/vEnhance/napkin/commit/b7264dfee3937aa519325b5227051123875cb51e. I also threw in a couple of chili peppers since it's apparently not so easy.
