### ISSUE TITLE
Typo: should have >= instead of =

### ISSUE THREAD

**Issue by rodrigo-castellon** [vEnhance/napkin#106]
Hi,
On page 208 in the newest version in the proof for the proposition, I _think_ it should be "n_r \geq pq" at the first sentence of the second paragraph instead of "n_r = pq", especially since you say a bit later that "we must have ... at least pq Sylow r-subgroups". This confused me when I was reading the proof. Correct me if I'm wrong.

**Comment by Kaiwen-S** [comment]
Hi. I think the sentence written in the book is correct. Here's my thought

1. We know that the Sylow number n_r is congruent to 1 mod r, meaning that n_r=1 or n_r \ge r+1, but he assumed in the preceding paragraph that n_r>1, so n_r \ge r+1. (will be applied to No. 3)
2. We also know that n_r divides pq (as you said in the comment), meaning that n_r=1 OR p OR q OR pq. We have only four possibilities because p, q are primes.
3. By "1", we already have n_r \ge r+1, so n_r \neq 1. By the assumption in the first paragraph of the proof, we have p<q<r WLOG, which means n_r \neq p and n_r \neq q, since they can NOT be congruent to 1 mod r.

Now there is only one possibility, which is n_r=pq. 

Please kindly correct me if my argument is flawed, Thank you. @vEnhance @rodrigo-castellon 

> Hi,
> On page 208 in the newest version in the proof for the proposition, I _think_ it should be "n_r \geq pq" at the first sentence of the second paragraph instead of "n_r = pq", especially since you say a bit later that "we must have ... at least pq Sylow r-subgroups". This confused me when I was reading the proof. Correct me if I'm wrong.

If everything is ok, then I think this issue can be closed.

**Comment by rodrigo-castellon** [comment]
Ohhhh yeah. My bad. I flipped around "n_r divides pq" in my head and was under the impression that n_r / pq was some integer. Thanks for pointing that out.
