### ISSUE TITLE
section headings in contents overlap enumeration

### ISSUE THREAD

**Issue by wen1now** [vEnhance/napkin#126]
<img width="113" alt="Screen Shot 2021-11-08 at 21 12 56" src="https://user-images.githubusercontent.com/27256263/142338641-4ad3c9a9-faf1-4dc2-9fad-393223cfbf99.png">

**Comment by vEnhance** [comment]
Thank you for reporting this!

I think something to the effect of
```
\RedeclareSectionCommand[tocnumwidth=4.2em]{part}
\RedeclareSectionCommand[tocnumwidth=4.2em]{chapter}
\RedeclareSectionCommand[tocnumwidth=2.8em]{section}
```
or similar lengths should deal with this, in the table of contents. But I am on the road now, so I won't be able to test it anytime soon. However, if someone does drop this in the preamble and finds the output acceptable, then submit a pull request :grin: otherwise I'll try it myself in 2-3 weeks.
