### ISSUE TITLE
Definition 32.2.2 seems wrong

### ISSUE THREAD

**Issue by SamZhang3** [vEnhance/napkin#214]
Definition 32.2.2 states the following:

> Let f : U → C as usual. A meromorphic function is a function which is holomorphic on U except at an isolated set S of points (meaning it is holomorphic as a function U \ S → C). For each p ∈ S, called a pole of f...

I don't think this is correct. For example, you could have f(x) = 1 if x = 0, and f(x) = 0 otherwise. Then f satisfies the definition above, since it is holomorphic at all nonzero x, so we can set S = {0}. However, f is clearly not meromorphic. There is also the case of essential singularities, like when f(x) = e^(1/x), which are not mentioned at all. In that case, the statement that the Laurent series "terminates on the trailing end" is false.

**Comment by vEnhance** [comment]
Re the first example, Def 32.2.2 has a second clause: there must be a Laurent series. So I think the example would not work here, because at 0 you cannot write a Laurent series with $m > 0$ and $c_{-m} \neq 0$ agreeing with the zero function near $z = 0$.

Perhaps the confusion is that Def 32.2.2 makes it look like the Laurent series is a conclusion, not part of the definition. I'll rewrite that now to say "the function $f$ is FURTHER REQUIRED TO ADMIT a Laurent series..." to eliminate that ambiguity.

Re essential singularity, my memory is that $e^{1/z}$ is not considered a meromorphic function on $\mathbb{C}$. See https://en.wikipedia.org/wiki/Meromorphic_function#Examples third example. So iirc this is intentional.

Abuse of Notation 32.2.4 goes into this more.

**Comment by vEnhance** [comment]
I addressed this in https://github.com/vEnhance/napkin/commit/2aa307848db7204eeea49097df413883b4116e27

Does that look right now?
