### ISSUE TITLE
Proof of Second Orthogonality

### ISSUE THREAD

**Issue by puzzlet** [vEnhance/napkin#63]
The following problem features the second orthogonality relation:

![image](https://user-images.githubusercontent.com/787236/72974150-e379d500-3e11-11ea-8638-f7f7630ee7f6.png)

Many books and notes[[1](http://people.brandeis.edu/~igusa/Math101bS07/Math101b_notesD.pdf)][[2](https://www.math.uni-bielefeld.de/~sek/select/rw2.pdf)] proves it by treating character table as a square matrix.

The _Napkin_'s approach in the Hint section seems a bit related but I don't see how:

![image](https://user-images.githubusercontent.com/787236/72975056-7bc48980-3e13-11ea-8116-5b369f330a7a.png)

Is this equivalent to other proofs? If so, how?

**Comment by vEnhance** [comment]
Closing this as I don't see an obvious equivalence to the usual proofs either (admittedly though, it has been a long time since I thought about this stuff). Anyone can feel free to re-open if they have a proposed way to see an equivalence (or non-equivalence). In the former case, I'll add it into the solution to the problem.
